### ISSUE TITLE
registry.npmjs.cf requests failing due to invalid SSL cert

### ISSUE THREAD

**Issue by broofa** [npmjs-cf/meta#1]
![image](https://user-images.githubusercontent.com/164050/35007107-70b6eef8-faad-11e7-9490-68421ef9fb72.png)

Also ...

![image](https://user-images.githubusercontent.com/164050/35007136-819a462a-faad-11e7-85f8-a3ff15aaa2f0.png)

**Comment by terinjokes** [comment]
Thanks. Expired. Now in my calendar to renew.

**Comment by broofa** [comment]
Awesome, thank you!  And in case I haven't said it before, thank you for hosting this service.  It's obviously essential to tools like npm.broofa.com and npm.anvaka.com.  You rock!
