### ISSUE TITLE
Failed to load https://registry.npmjs.cf/react-router-dom/%5E4.2.2: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://npm.broofa.com' is therefore not allowed access. The response had HTTP status code 526.

### ISSUE THREAD

**Issue by broofa** [npmjs-cf/meta#3]
Getting this on npm.broofa.com e.g. See network requests in Chrome developer console when fetching http://npm.broofa.com/?q=request

**Comment by terinjokes** [comment]
Fixed. Thanks.

**Comment by terinjokes** [comment]
@broofa Doesn't look like "^4.2.2" versions work anymore. FYI.

**Comment by broofa** [comment]
@terinjokes Yeah, I've been seeing that in my logs.  'Looks like npmjs.org doesn't allow semver ranges any more?  (Not sure if/when that changed.)  I'm working on a fix for it in NPMGraph.
