### ISSUE TITLE
Missing CORS headers for 4XX responses

### ISSUE THREAD

**Issue by broofa** [npmjs-cf/meta#4]
NPM registry sometimes responds with 4XX errors (E.g. 401's due to https://github.com/npm/registry/issues/34, or 404's for invalid module names).  Even though the CF mirror passes these responses on to the client, they are muted due to lack of CORS headers.

The end result is that errors on npm.broofa.com all manifest as aborted requests with `status = 0`, so my ability to surface errors in an intelligent way is limited.
 
Would it be possible to add CORS headers to these error responses?

**Comment by terinjokes** [comment]
Done

**Comment by broofa** [comment]
Sweet! As usual, you rock. :-)
