### ISSUE TITLE
Server closes connection before sending all bytes of the tarball

### ISSUE THREAD

**Issue by mischnic** [npmjs-cf/meta#6]
It looks like the server closes the connection before sending the whole body:

```
$ curl https://registry.npmjs.cf/react-dom/-/react-dom-17.0.1.tgz -LO
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 18  727k   18  134k    0     0   151k      0  0:00:04 --:--:--  0:00:04  151k
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)

$ curl https://registry.npmjs.cf/react-dom/-/react-dom-17.0.1.tgz -LO --http1.1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 20  727k   20  152k    0     0   155k      0  0:00:04 --:--:--  0:00:04  155k
curl: (18) transfer closed with 588581 bytes remaining to read
```
Other failing one: https://registry.npmjs.cf/@babel/parser/-/parser-7.12.11.tgz , https://registry.npmjs.cf/@parcel/source-map/-/source-map-2.0.0-alpha.4.19.tgz, https://registry.npmjs.cf/node-gyp/-/node-gyp-7.1.2.tgz 

Some packages work fine, e.g. https://registry.npmjs.cf/lodash-es/-/lodash-es-4.17.15.tgz,

**Comment by terinjokes** [comment]
Due to radical changes npm did to their infrastructure, this project is in maintenance mode. I'd recommend switching back to the normal registry.

**Comment by mischnic** [comment]
That's very unfortunate. If only npmjs.org would send CORS headers...

**Comment by terinjokes** [comment]
I'll keep the CORS part running for now, I just might not put much effort into fixing tarballs. I thought these were returned in the JSON with registry.npmjs.org URLs?

**Edit** to be clear, I will look at this, to see if it's an easy fix.

**Comment by mischnic** [comment]
> I thought these were returned in the JSON with registry.npmjs.org URLs?

Yes, they are. But they of course still don't work due to CORS, so I rewrite them to `registry.npmjs.cf` which worked fine sometimes.

>  I will look at this, to see if it's an easy fix.

Thank you! 🙏

**Comment by terinjokes** [comment]
Ah, so you're fetching the tarballs over CORS? That's not a use case I expected.

**Comment by mischnic** [comment]
😬 For running Yarn in the browser (resolution + installing)

**Comment by terinjokes** [comment]
Looks like I was able to resolve this.

```console
$ curl https://registry.npmjs.cf/react-dom/-/react-dom-17.0.1.tgz -LO 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  727k  100  727k    0     0  2245k      0 --:--:-- --:--:-- --:--:-- 2245k

$ shasum react-dom-17.0.1.tgz 
1de2560474ec9f0e334285662ede52dbc5426fc6  react-dom-17.0.1.tgz

$ curl -Ss https://registry.npmjs.cf/react-dom/|jq '.versions["17.0.1"].dist.shasum' -r
1de2560474ec9f0e334285662ede52dbc5426fc6
```

**Comment by mischnic** [comment]
Thank you!
