### ISSUE TITLE
Deprecating npmjs.cf

### ISSUE THREAD

**Issue by terinjokes** [npmjs-cf/meta#8]
Hello folks,

I started npmjs.cf in 2014 as a mirror of the official npm registry, replicating the fullfatdb CouchDB, and modifying the CouchApp to support being hosted on another domain. At some point I added support for CORS, allowing for webapps to make XHR/fetch requests for package metadata directly from the browser.

Due to several architecture changes during the time of the npm company, and difficulty in maintaining CouchDB replication as a single person, the site became a read-through cache, and eventually simple a proxy adding CORS headers.

I believe CORS usage to be the only remaining users of npmjs.cf. The upstream registry added CORS headers last year, removing this final benefit.

Over the past few years, it's become more evident that using a ccTLD for "critical" infrastructure was a mistake. The Go [netaddr](https://github.com/go4org/netipx/tree/f1b76eb4bb35e16dd7db0b682e2ccc56c72635da#faq) module was using the `.af` ccTLD, which became Taliban controlled. More recently, the future of [Freenom](https://krebsonsecurity.com/2023/03/sued-by-meta-freenom-halts-domain-registrations/) has become ambiguous. For the safety of the JS community, I think it's time to finally deprecate npmjs.cf.

Over the next few days I plan to update the homepage to link to this discussion, and add a new response header also linking to this discussion, along with posting this message to social media. I'll schedule a few "brownouts" of the proxy to attempt to get the attention of remaining users.

I do plan on keeping the domain registered for a reasonable amount of time, at least as long as Freenom (or successors) allow.

/cc @mylesborins @broofa @mischnic

**Comment by broofa** [comment]
Sounds good, Terin.

FWIW, `npmgraph` switched off of `npmjs.cf` [last year](https://github.com/npmgraph/npmgraph/pull/129).  (My apologies for not mentioning this earlier.)

Thanks for all your work and support over the years.  Your mirror is what made `npmgraph` possible!

<image width=400 src="https://media.giphy.com/media/3o6ZsUJ44ffpnAW7Dy/giphy.gif" />

**Comment by terinjokes** [comment]
Deprecation notice added to the homepage, the news page (I forgot there even _was_ a news page), and also the registry response.

```
$ curl -ISs https://registry.npmjs.cf | grep deprecation
deprecation-notice: npmjs.cf has been deprecated. For more details, visit https://github.com/npmjs-cf/meta/issues/8
```

**Comment by terinjokes** [comment]
The server providing the proxying has been terminated and wiped, DNS entries for the WWW site and registry proxy have been removed. As mentioned above, I'll do my best to keep hold of the domain registration for the foreseeable future to prevent any nefarious usage.

---

So long and thanks for all the fish. :dolphin:
